[package]
name = "git-todo"
version = "0.0.3"
edition = "2018"

[dependencies]
exitcode = "1.1.2"
getopts = "0.2.21"
git2 = { version = "0.13.11", features = ["vendored-openssl"] }
thiserror = "1.0.20"
