#!/bin/sh

# Show TODOs since base branch

git diff --diff-filter=a -S'TODO' "$(git oldest-ancestor)"... |
	egrep --after-context 1 '^\+.*\bTODO\b' |
	sed 's/^+[[:space:]]*//'


# Want:
# - filename
# - line number

# Use git blame?

# fgrep -A 1 -n TODO $(git diff --name-only $(git oldest-ancestor)... )
# ^ not quite the same thing, as it will catch old TODOs in updated files

# https://stackoverflow.com/questions/23298812/python-unified-diff-with-line-numbers-from-both-files
# diff --unchanged-line-format=' %.2dn %L' --old-line-format="-%.2dn %L" --new-line-format="+%.2dn %L" <(git show @~:app/module/background/nativeMessageManager.js) app/module/background/nativeMessageManager.js
